//
//  FormAccountInterfaces.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FormAccountWireframeInterface: WireframeInterface {
}

protocol FormAccountViewInterface: ViewInterface {
}

protocol FormAccountPresenterInterface: PresenterInterface {
}

protocol FormAccountInteractorInterface: InteractorInterface {
}
