//
//  FormAccountInteractor.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FormAccountInteractor {
}

// MARK: - Extensions -

extension FormAccountInteractor: FormAccountInteractorInterface {
}
