//
//  VerificationCodeViewController.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class VerificationCodeViewController: UIViewController {

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var infoLabel: UILabel!
    @IBOutlet weak var resendButton: UIButton!
    @IBOutlet weak var sendButton: UIButton!
    
    @IBOutlet weak var field1: UITextField!
    @IBOutlet weak var field2: UITextField!
    @IBOutlet weak var field3: UITextField!
    @IBOutlet weak var field4: UITextField!
    @IBOutlet weak var field5: UITextField!
    
    
    // MARK: - Public properties -
    var presenter: VerificationCodePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setUpTextField()
        configureBackButton()
        setUpStyles()
    }
    
    private func setUpTextField() {
        field1.delegate = self
        field2.delegate = self
        field3.delegate = self
        field4.delegate = self
        field5.delegate = self
    }
    
    private func setUpStyles() {
        titleLabel.font = UIFont(name: "Montserrat-SemiBold", size: 24.0)!
        titleLabel.textColor = .black1
        descriptionLabel.font = UIFont(.MontserratRegular, .s12)
        descriptionLabel.textColor = .black1
        sendButton.greenButton()
        resendButton.redButton2()
    }
    
    private func configureBackButton() {
        navigationItem.configureBarButton(
            imageName: "backArrow",
            tintColor: .green2,
            target: self,
            selector: #selector(backAction),
            side: .left
        )
    }
    
    @objc func backAction() {
        if let navigation = navigationController {
            navigation.popViewController(animated: true)
        } else {
            self.dismiss(animated: true, completion: nil)
        }
    }
    
    @IBAction func resendButtonAction(_ sender: Any) {
    }
    
    @IBAction func sendButtonAction(_ sender: Any) {
        guard let navigation = navigationController else { return }
        navigation.pushWireframe(FormAccountWireframe())
    }
    
}

// MARK: - Extensions -
extension VerificationCodeViewController: VerificationCodeViewInterface {
}

extension VerificationCodeViewController: UITextFieldDelegate {
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        switch textField.tag {
        case 1: field2.becomeFirstResponder()
        case 2: field3.becomeFirstResponder()
        case 3: field4.becomeFirstResponder()
        case 4: field5.becomeFirstResponder()
        default: break
        }
    }
}

