//
//  SectionsWireframe.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SectionsWireframe: BaseWireframe<SectionsViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = SectionsViewController()
        super.init(viewController: moduleViewController)

        let interactor = SectionsInteractor()
        let presenter = SectionsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SectionsWireframe: SectionsWireframeInterface {
}
