//
//  SectionsPresenter.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SectionsPresenter {

    // MARK: - Private properties -

    private unowned let view: SectionsViewInterface
    private let interactor: SectionsInteractorInterface
    private let wireframe: SectionsWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: SectionsViewInterface,
        interactor: SectionsInteractorInterface,
        wireframe: SectionsWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension SectionsPresenter: SectionsPresenterInterface {
}
