//
//  FormAccountPresenter.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FormAccountPresenter {

    // MARK: - Private properties -

    private unowned let view: FormAccountViewInterface
    private let interactor: FormAccountInteractorInterface
    private let wireframe: FormAccountWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: FormAccountViewInterface,
        interactor: FormAccountInteractorInterface,
        wireframe: FormAccountWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension FormAccountPresenter: FormAccountPresenterInterface {
}
