//
//  CreateAccountWireframe.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateAccountWireframe: BaseWireframe<CreateAccountViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = CreateAccountViewController()
        super.init(viewController: moduleViewController)

        let interactor = CreateAccountInteractor()
        let presenter = CreateAccountPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CreateAccountWireframe: CreateAccountWireframeInterface {
}
