//
//  VerificationCodePresenter.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class VerificationCodePresenter {

    // MARK: - Private properties -

    private unowned let view: VerificationCodeViewInterface
    private let interactor: VerificationCodeInteractorInterface
    private let wireframe: VerificationCodeWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: VerificationCodeViewInterface,
        interactor: VerificationCodeInteractorInterface,
        wireframe: VerificationCodeWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension VerificationCodePresenter: VerificationCodePresenterInterface {
}
