//
//  VerificationCodeWireframe.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class VerificationCodeWireframe: BaseWireframe<VerificationCodeViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = VerificationCodeViewController()
        super.init(viewController: moduleViewController)

        let interactor = VerificationCodeInteractor()
        let presenter = VerificationCodePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension VerificationCodeWireframe: VerificationCodeWireframeInterface {
}
