//
//  DetailSectionInterfaces.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailSectionWireframeInterface: WireframeInterface {
}

protocol DetailSectionViewInterface: ViewInterface {
}

protocol DetailSectionPresenterInterface: PresenterInterface {
}

protocol DetailSectionInteractorInterface: InteractorInterface {
}
