//
//  DetailSectionInteractor.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailSectionInteractor {
}

// MARK: - Extensions -

extension DetailSectionInteractor: DetailSectionInteractorInterface {
}
