//
//  DetailSectionViewController.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailSectionViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DetailSectionPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension DetailSectionViewController: DetailSectionViewInterface {
}
