//
//  DetailSectionPresenter.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailSectionPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailSectionViewInterface
    private let interactor: DetailSectionInteractorInterface
    private let wireframe: DetailSectionWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: DetailSectionViewInterface,
        interactor: DetailSectionInteractorInterface,
        wireframe: DetailSectionWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension DetailSectionPresenter: DetailSectionPresenterInterface {
}
