//
//  LoginMainInterfaces.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol LoginMainWireframeInterface: WireframeInterface {
}

protocol LoginMainViewInterface: ViewInterface {
}

protocol LoginMainPresenterInterface: PresenterInterface {
}

protocol LoginMainInteractorInterface: InteractorInterface {
}
