//
//  LoginMainWireframe.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginMainWireframe: BaseWireframe<LoginMainViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = LoginMainViewController()
        super.init(viewController: moduleViewController)

        let interactor = LoginMainInteractor()
        let presenter = LoginMainPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LoginMainWireframe: LoginMainWireframeInterface {
}
