//
//  LoginMainPresenter.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginMainPresenter {

    // MARK: - Private properties -

    private unowned let view: LoginMainViewInterface
    private let interactor: LoginMainInteractorInterface
    private let wireframe: LoginMainWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: LoginMainViewInterface,
        interactor: LoginMainInteractorInterface,
        wireframe: LoginMainWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginMainPresenter: LoginMainPresenterInterface {
}
