//
//  CartWireframe.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 18/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CartWireframe: BaseWireframe<CartViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = CartViewController()
        super.init(viewController: moduleViewController)

        let interactor = CartInteractor()
        let presenter = CartPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CartWireframe: CartWireframeInterface {
}
