//
//  LoginMainViewController.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginMainViewController: UIViewController {

    @IBOutlet weak var createAccount: UIButton!
    @IBOutlet weak var loginButton: UIButton!
    @IBOutlet weak var forgotPassword: UIButton!
    @IBOutlet weak var emailField: UITextField!
    @IBOutlet weak var passwordField: UITextField!
    @IBOutlet weak var titleLabel: UILabel!
    
    
    // MARK: - Public properties -
    var presenter: LoginMainPresenterInterface!

    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func loginButtonAction(_ sender: Any) {
    }
    
    @IBAction func createAccountAction(_ sender: Any) {
    }
    
    @IBAction func forgotPassword(_ sender: Any) {
    }
    
}

// MARK: - Extensions -

extension LoginMainViewController: LoginMainViewInterface {
}
