//
//  HomeInterfaces.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 13/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func goToDetail()
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func goToDetail()
}

protocol HomeInteractorInterface: InteractorInterface {
}
