//
//  CreateAccountViewController.swift
//  PronacaShareholders
//
//  Created by CarlosDz on 9/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateAccountViewController: UIViewController {

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var mailField: UITextField!
    @IBOutlet weak var sendButton: UIButton!
    
    // MARK: - Public properties -
    var presenter: CreateAccountPresenterInterface!

    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func sendButtonAction(_ sender: Any) {
        guard let navigation = navigationController else { return }
        navigation.pushWireframe(FormAccountWireframe())
    }
    
    
}

// MARK: - Extensions -

extension CreateAccountViewController: CreateAccountViewInterface {
}
